apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: example-compliancesuite
spec:
  autoApplyRemediations: false
  scans:
      - name: workers-scan
        profile: xccdf_org.ssgproject.content_profile_coreos-ncp
        content: ssg-ocp4-ds.xml
        contentImage: quay.io/jhrozek/ocp4-openscap-content:latest
        nodeSelector:
            node-role.kubernetes.io/worker: ""
