apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      name: compliance-operator
  template:
    metadata:
      labels:
        name: compliance-operator
    spec:
      serviceAccountName: compliance-operator
      containers:
        - name: compliance-operator
          image: "quay.io/compliance-operator/compliance-operator:scratch_34501-20200709183353"
          command:
          - compliance-operator
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "compliance-operator"
            - name: OPENSCAP_IMAGE
              # Hardcoding this temporarily until its propagated to CI
              value: "quay.io/compliance-operator/openscap-ocp:scratch_63799-20200709162434"
            - name: OPERATOR_IMAGE
              value: "quay.io/compliance-operator/compliance-operator:scratch_34501-20200709183353"
            - name: DEFAULT_PROFILE_BUNDLES_IMAGE
              value: "quay.io/complianceascode/ocp4:latest"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
