apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-operator
spec:
  replicas: 3
  selector:
    matchLabels:
      name: compliance-operator
  template:
    metadata:
      labels:
        name: compliance-operator
    spec:
      serviceAccountName: compliance-operator
      containers:
        - name: compliance-operator
          image: image-registry.openshift-image-registry.svc:5000/openshift-compliance/compliance-operator
          command:
          - compliance-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "compliance-operator"
            - name: OPENSCAP_IMAGE
              value: "quay.io/mrogers950/openscap-ocp:upstream"
            - name: LOG_COLLECTOR_IMAGE
              value: "image-registry.openshift-image-registry.svc:5000/openshift-compliance/resultscollector:latest"
            - name: RESULT_SERVER_IMAGE
              value: "image-registry.openshift-image-registry.svc:5000/openshift-compliance/resultserver:latest"
            - name: REMEDIATION_AGGREGATOR_IMAGE
              value: "image-registry.openshift-image-registry.svc:5000/openshift-compliance/remediation-aggregator:latest"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
